/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafikus0407;

import java.util.Random;

/**
 *
 * @author Balazs
 */
public class ablak extends javax.swing.JFrame {
    public int osztando;
    public int oszto;
    public int hanyados;
    
    public ablak() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        txtValasz = new javax.swing.JTextField();
        btnEllenorzes = new javax.swing.JButton();
        lbMuvelet = new javax.swing.JLabel();
        lbMegoldas = new javax.swing.JLabel();
        lbValasz = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStatisztika = new javax.swing.JTextArea();
        lbStatisztika = new javax.swing.JLabel();
        lbFeladatDb = new javax.swing.JLabel();
        lbSzazalek = new javax.swing.JLabel();
        btnMegoldas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMuveletek = new javax.swing.JMenu();
        mnuOsszeadas = new javax.swing.JMenu();
        mnuKivonas = new javax.swing.JMenu();
        mnuSzorzas = new javax.swing.JMenu();
        mnuOsztas = new javax.swing.JMenu();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEllenorzes.setText("Ellenőrzés");
        btnEllenorzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEllenorzesActionPerformed(evt);
            }
        });

        lbMuvelet.setText("Művelet");

        lbMegoldas.setText("A válaszod: ");

        lbValasz.setText("Válaszod:");

        txtStatisztika.setColumns(20);
        txtStatisztika.setRows(5);
        txtStatisztika.setText("Összeadás: 0\nKivonás: 0\nSzorzás: 0\nOsztás: 0");
        jScrollPane1.setViewportView(txtStatisztika);

        lbStatisztika.setText("Statisztika");

        lbFeladatDb.setText("Feladatok száma");

        lbSzazalek.setText("Százalék: x%");

        btnMegoldas.setText("Megoldás");
        btnMegoldas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegoldasActionPerformed(evt);
            }
        });

        mnuMuveletek.setText("Műveletek");

        mnuOsszeadas.setText("Összeadás");
        mnuMuveletek.add(mnuOsszeadas);

        mnuKivonas.setText("Kivonás");
        mnuMuveletek.add(mnuKivonas);

        mnuSzorzas.setText("Szorzás");
        mnuMuveletek.add(mnuSzorzas);

        mnuOsztas.setText("Osztás");
        mnuOsztas.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuOsztasMenuSelected(evt);
            }
        });
        mnuMuveletek.add(mnuOsztas);

        jMenuBar1.add(mnuMuveletek);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbMuvelet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbValasz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtValasz)
                    .addComponent(lbMegoldas, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMegoldas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEllenorzes, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbStatisztika)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbSzazalek, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbFeladatDb, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbMuvelet, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbValasz)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValasz, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEllenorzes))
                        .addGap(18, 18, 18)
                        .addComponent(lbMegoldas, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbStatisztika)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnMegoldas))))
                .addGap(18, 18, 18)
                .addComponent(lbFeladatDb)
                .addGap(26, 26, 26)
                .addComponent(lbSzazalek)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void szamolas() {
        Random r = new Random();
        boolean jo;
        osztando = r.nextInt(101);
        
        do {
            oszto = r.nextInt(101) + 1;
            hanyados = osztando / oszto;
            jo = osztando % oszto == 0 && hanyados <= 100;
        } while (!jo);
        
        kiirMuvelet(osztando, oszto);
    }
    
    public void kiirMuvelet(int osztando, int oszto){
        lbMuvelet.setText(osztando + "/" + oszto + " = ");
    }

    private void mnuOsztasActionPerformed(java.awt.event.ActionEvent evt) {                                          
        szamolas();
    }                 
    private void btnEllenorzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEllenorzesActionPerformed
        try {
            int valasz = Integer.parseInt(txtValasz.getText());
        if (valasz == hanyados) {
            lbMegoldas.setText("Helyes válasz!");
        } else {
            lbMegoldas.setText("Rossz válasz!");
        }
        } catch (NumberFormatException e) {
            lbMegoldas.setText("Pozitív egész számot adjon meg!");
        }
        
    }//GEN-LAST:event_btnEllenorzesActionPerformed

    private void btnMegoldasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegoldasActionPerformed
        //txtStatisztika.setText("osztás: 1");
    }//GEN-LAST:event_btnMegoldasActionPerformed

    private void mnuOsztasMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuOsztasMenuSelected
        szamolas();
    }//GEN-LAST:event_mnuOsztasMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEllenorzes;
    private javax.swing.JButton btnMegoldas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbFeladatDb;
    private javax.swing.JLabel lbMegoldas;
    private javax.swing.JLabel lbMuvelet;
    private javax.swing.JLabel lbStatisztika;
    private javax.swing.JLabel lbSzazalek;
    private javax.swing.JLabel lbValasz;
    private javax.swing.JMenu mnuKivonas;
    private javax.swing.JMenu mnuMuveletek;
    private javax.swing.JMenu mnuOsszeadas;
    private javax.swing.JMenu mnuOsztas;
    private javax.swing.JMenu mnuSzorzas;
    private javax.swing.JTextArea txtStatisztika;
    private javax.swing.JTextField txtValasz;
    // End of variables declaration//GEN-END:variables
}
